// Generated by CoffeeScript 1.6.2
exports.listen = function(port) {
  var WebSocket, server;

  WebSocket = require("ws").Server;
  server = new WebSocket({
    port: port
  });
  return {
    each: function(handler) {
      var route, ws;

      ws = {};
      route = {};
      ws.on = function(key, callback) {
        return route[key] = callback;
      };
      return server.on("connection", function(socket) {
        ws.emit = function(key, value) {
          return socket.send(JSON.stringify({
            key: key,
            value: value
          }));
        };
        socket.on("message", function(data) {
          var _name;

          data = JSON.parse(data);
          return typeof route[_name = data.key] === "function" ? route[_name](data.value) : void 0;
        });
        return handler(ws);
      });
    }
  };
};
